### ISSUE TITLE
Boxy URDF description crashes in RViz

### ISSUE THREAD

**Issue by gaya-** [code-iai/iai_robots#13]
RViz complains about the WSG meshes by saying that Assymp cannot find them although they are present in the ROS package.
Can't say more about this but one thing is clear: RViz crashes when you try to visualize the URDF.

**Comment by airballking** [comment]
@gaya- could you please compare with https://github.com/code-iai/iai_robots/pull/12 ? The problems sound related...

**Comment by gaya-** [comment]
I figured out what was wrong. I was trying to visualize RobotState and not RobotModel. Although both work with the PR2, I guess it's ok if RobotState crashes, as long as RobotModel is ok.
