### ISSUE TITLE
Problem with .stl's and MoveIt!

### ISSUE THREAD

**Issue by ichumuh** [code-iai/iai_robots#17]
I tried to create a MoveIt! config package for boxy with the moveit_setup_assistant. When i loaded boxy_description.urdf.xacro the program crashed with the following error message:

```
*** Error in
`/opt/ros/indigo/lib/moveit_setup_assistant/moveit_setup_assistant':
malloc(): memory corruption: 0x00000000031a5a70 ***
================================================================================REQUIRED
process [moveit_setup_assistant-2] has died!
process has died [pid 22737, exit code -6, cmd
/opt/ros/indigo/lib/moveit_setup_assistant/moveit_setup_assistant
__name:=moveit_setup_assistant
__log:=/home/ichumuh/.ros/log/377795c4-d440-11e5-9545-f0def1aaa816/moveit_setup_assistant-2.log].
log file:
/home/ichumuh/.ros/log/377795c4-d440-11e5-9545-f0def1aaa816/moveit_setup_assistant-2*.log
Initiating shutdown!
================================================================================
```

Since i had problems with the .stl meshes before, I tried to convert them with "ctmconv" into a different format, which fixed the problem. Then I tried to just convert the .stl to .stl, which also seems to fix it. I also tried to only convert a subset and leave the others as they are, but it always led to the same problem. I haven't tried every possible combination though.
I also wrote a little python script, that replaces every .stl in iai_robots:

```
#!/usr/bin/env python
from glob import glob
from subprocess import call
import rospkg

"""
This script rewrites every .stl in the iai_robots repo.
"""

def replace_stl(dir):
    """
    Converts every .stl in dir and its subdirectories into a new .stl.
    :param dir: string
        target directory
    """
    files = glob(dir+"*.stl")
    for f in files:
        call(["ctmconv", f, f])
    dirs = glob(dir+"*/")
    for d in dirs:
        replace_stl(d)

rospack = rospkg.RosPack()
dir = rospack.get_path("iai_boxy_base")+"/../"
replace_stl(dir)
```

**Comment by mgvargas** [comment]
I have the same issue while loading boxy's URDF boxy_description.urdf, I already used make_urdf.sh to transform the .xacro file to a .urdf

`[ INFO] [1461225946.538365816]: Loaded boxy_description robot model.
[ INFO] [1461225946.538679185]: Setting Param Server with Robot Description
[ INFO] [1461225946.608057414]: Robot semantic model successfully loaded.
[ INFO] [1461225946.608168998]: Setting Param Server with Robot Semantic Description
[ INFO] [1461225946.638783020]: Loading robot model 'boxy_description'...
[ INFO] [1461225946.638893898]: No root joint specified. Assuming fixed joint
*** Error in `/opt/ros/indigo/lib/moveit_setup_assistant/moveit_setup_assistant': malloc(): memory corruption: 0x0000000002463fa0 ***
Aborted (core dumped)
`
I could load the URDF after commenting several parts:
 -  New Neck Assembly
 - Old neck assembly
 - Kinnect2
 - kms_40_xacro
 - left_wrist_optical_frame_x
 - left_wrist_optical_frame
 - left_wrist_optical_joint_x

`
        
        


        
       


        

        
	
	
	
	
	

	
        

        
       

        
        
       `

`        
      
      

        
       
        



        
       
        

	`

`        
        
       `

I think one or several of this meshes could be damaged

**Comment by amaldo** [comment]
The meshes have been fixed, as far as I know. It was caused by the default STL exporter from Inventor. It seems to add extra fields at the end related to color, which the STL parser can't handle.
