### ISSUE TITLE
iai_weiss_wsg50  URDF needs fingers (and joints)

### ISSUE THREAD

**Issue by amaldo** [code-iai/iai_robots#4]
The gripper should have two fingers, and they need joints. And possibly a tranmission linking them so that there is really only 1 DOF.

**Comment by airballking** [comment]
The fingers are now showing up in rviz. @jannikb fixed that. 

However, the transmission is still simple. Meaning: We still have 2 DOF instead of 1 for each gripper.

**Comment by airballking** [comment]
Done.
